### ISSUE TITLE
Accessing the underlying sqlite database in a Moor stash

### ISSUE THREAD

**Issue by ilikerobots** [ivoleitao/stash#18]
I'm using stash as a non-volatile LRU store of records representing documents.  I will cache these forever, but only cache a limited number.  I would like to implement a simple text search (against titles, keywords, etc) of the stored documents.  

I know the Moor stash uses an sqlite database via moor, so I wonder if you have any thoughts on how the underlying sqlite database (through sqlite, sqflite, or moor packages perhaps) could be accessed and queried.

I've tried opening the file directly with code such as 
```
_searchDatabase = await LazyDatabase(() async {
       final dir = await getApplicationDocumentsDirectory();
       final path = p.join(dir.path, "stash_documents.moordb");
       final file = File(path);
       return VmDatabase(file);
     });
```
but I was unable to query, receiving a LateInitializationError instead.

**Comment by ivoleitao** [comment]
Hello,

So this one is probably a bit more complex but I think it's doable.

When you call `newSqliteFileCache` to create a new cache I'm doing the following:

```dart
  return Cache.newCache(
      SqliteStore(
          SqliteFileAdapter(file,
              logStatements: databaseLog, setup: databaseSetup),
          codec: codec,
          fromEncodable: fromEncodable),
      name: cacheName,
      expiryPolicy: expiryPolicy,
      sampler: sampler,
      evictionPolicy: evictionPolicy,
      maxEntries: maxEntries,
      cacheLoader: cacheLoader,
      eventListenerMode: eventListenerMode);
```

There's a bunch of actors in play:
* SqliteStore
* SqliteFileAdapter

On the SqliteStore you just have access to the methods that provide the store API. Internally I call DAO classes that operate over the tables but still it's constrained to those operations. The adapter however is more interesting has it provides a bridge between the underlying moor datastore (File, Memory etc) and the store concepts of stash

On the API of the adapter I ask for the override of `QueryExecutor executor()`. This method on the SqliteFileAdapter has the following:

```dart
  @override
  QueryExecutor executor() {
    return VmDatabase(file,
        logStatements: logStatements ?? false, setup: setup);
  }
```

I don't know all the details of moor but this object gives you raw access to the DB. So if you implement you adapter using the existing implementation as a guide and get hold of the executor, I believe you can do what you intend. Notice that this is really way off the intended use of the lib or even of moor because I think I have seen the author cautioning on the use of this.

The other way out is implementing you own store and controlling everything. You will just need an additional DAO for this it's quite easy. The problem is that this classes are all generated from a definition so there is not a lot of extension points for this advanced scenarios.

**Comment by ilikerobots** [comment]
I wasn't able to successfully use the QueryAdapter from _mySqlAdapter!.executor() directly as I would receive:

```Unhandled Exception: 'package:moor/src/runtime/executor/helpers/engines.dart': Failed assertion: line 44 pos 12: '_ensureOpenCalled': is not true.```

and I can't find any way to call ensureOpen(user) with a valid user.


However, I did find that 
```
theSqlAdapter.dao.customSelect('select * from Cache where name = ?',
                                                    variables: [Variable<String>('storage_documents')]);
```
worked well.

However, unfortunately I realized I receive back records such as:

```{name: storage_documents, key: d0d76ff5-082f-406a-ba60-25b36db4a433, expiry_time: 2022-07-15T17:00:25.839024, creation_time: 2021-07-20T17:00:25.839024, access_time: 2021-07-20T17:00:25.839024, update_time: 2021-07-20T17:00:25.839024, hit_count: 0, extra: null, value: [218, 12, 68, 123, 34, 67, 111, 110, 116, 101, 110, 116, 73, 100, 34, 58, 34, 100, 48, 100, 55, 54, 102, 102, 53, 45, 48, 56, 50, 102, 45, 52, 48, 54, 97, 45, 98, 97, 54, 48, 45, 50, 53, 98, 51, 54, 100, 98, 52, 97, 52, 51, 5.....```

As it looks like the value is encoded (by msgpack?) , I wouldn't be able to do any useful sql text queries against my data (e.g. search by title) using custom selects anyway.

**Comment by ivoleitao** [comment]
Hi, yes it's encoded by msgpack as I see cache object as generic only implementing a way to serialise them. What I do is to first json serialise and then encode with msgpack. However you can change the encoder to output only json string. The real problem is that the column on the db is a blob :-/. See [here](https://github.com/ivoleitao/stash/blob/develop/packages/stash_sqlite/lib/src/sqlite/table/cache_table.dart)

At this point I would say that you really need a very specific thing. So, without a specific implementation of a storage I'm not sure you can achieve your intent.

In this case you would need to change the column to clob and create some operations on a specific dao still implementing the CacheStore API

**Comment by ilikerobots** [comment]
Got it, appreciate all your thoughts.  I'm going to implement this outside of stash with a separate search.  Storing is easy, the only nuance is using the eviction and expiration events on the stash to remove records from the search database, but that's also not very difficult.
