### ISSUE TITLE
Moor warning: It looks like you've created the database class CacheDatabase multiple times

### ISSUE THREAD

**Issue by ilikerobots** [ivoleitao/stash#19]
In my app log, I receive the following warning numerous times when using moor stashes:
```
I/flutter (10409): WARNING (moor): It looks like you've created the database class CacheDatabase multiple times. When these two databases use the same QueryExecutor, race conditions will occur and might corrupt the database. 
I/flutter (10409): Try to follow the advice at https://moor.simonbinder.eu/faq/#using-the-database or, if you know what you're doing, set moorRuntimeOptions.dontWarnAboutMultipleDatabases = true
I/flutter (10409): Here is the stacktrace from when the database was opened a second time:
I/flutter (10409): #0      GeneratedDatabase._handleInstantiated (package:moor/src/runtime/api/db_base.dart:88:30)
I/flutter (10409): #1      new GeneratedDatabase (package:moor/src/runtime/api/db_base.dart:59:12)
I/flutter (10409): #2      new _$CacheDatabase (package:stash_sqlite/src/sqlite/cache_database.g.dart:480:38)
I/flutter (10409): #3      new CacheDatabase (package:stash_sqlite/src/sqlite/cache_database.dart:22:43)
I/flutter (10409): #4      new SqliteAdapter (package:stash_sqlite/src/sqlite/sqlite_adapter.dart:39:19)
I/flutter (10409): #5      new SqliteFileAdapter (package:stash_sqlite/src/sqlite/sqlite_adapter.dart:97:9)
I/flutter (10409): #6      newSqliteFileCache (package:stas
```

I am using several moor stashes in my app, but I believe each is correctly instantiated each only once.   The building of the first cache does not trigger the warning, but all subsequent caches do.

I can build a min reproducible example or test case, but before I spent time on it I wanted to check if it was a known problem or perhaps, as the warning suggests, I should simply enable the `dontWarnAboutMultipleDatabases` flag.

**Comment by ivoleitao** [comment]
Hi,

Yes this one is caused by more than one instance of the CacheStore class but it's quite easy to solve. Bellow an example that reproduces this scenario:

```dart
  test('multiple stores', () {
    final cache1 = newSqliteMemoryCache(cacheName: 'cache1');
    final cache2 = newSqliteMemoryCache(cacheName: 'cache2');
  });
```

This gives you the exception above. The solution is to store the caches in a single db. You can achieve that if you create the storage first and reuse it. ~The only thing that you need to be careful with is to use different cache names~. Well actually no as if the name is not provided I generate a uuid. Be careful with this with persistency i.e. `newSqliteFileCache` as it creates a different file every time

An example bellow:

```dart
  test('single store', () {
    final store = SqliteStore(SqliteMemoryAdapter());

    final cache1 = Cache.newCache(store, name: 'cache1');
    final cache2 = Cache.newCache(store, name: 'cache2');
  });
```

I should probably revise the global methods to allow the reuse of a store to avoid the need to resort to the low level API like the above. There's still a problem though which I'm not sure if I'm covering which is moor being used separately for some other feature on your app. I believe you will get the same warning on that case. However you shouldn't get it for multiple caches

**Comment by ilikerobots** [comment]
Thanks! Rewriting as you suggest above works beautifully.
