### ISSUE TITLE
stash_sembast, stash_hive, etc. should support the web. 

### ISSUE THREAD

**Issue by jifalops** [ivoleitao/stash#20]
The backend implementations of stash should support running on the web if the associated package supports running on the web. For example, `sembast` is marked as being `JS` compatible on pub.dev, but `stash_sembast` is not.

**Comment by ivoleitao** [comment]
Hi, 

I've fixed this issue in the latest release. The API had to change slightly for Sembast but for Hive only an internal change was needed. Additionally to more directly support sembast_web a new package stash_sembast_web was created and should be used on flutter web instead of stash_sembast just like the original package.
