### ISSUE TITLE
Cache Lookup / Query / Finder

### ISSUE THREAD

**Issue by naturallymitchell** [ivoleitao/stash#27]
@ivoleitao, what do you think about adding a way to interact with records, ie filter, sort, select, etc?

A powerful expression evaluator / search library is already available for Collections, [JMESPath](https://github.com/vikesh-raj/jmespath).

**Comment by ivoleitao** [comment]
Humm interesting. How do you imagine this being used ? Search in the retrieved objects or search across all the stored objects ?

The problem is that every backend is different and has more or less capabilities. Some of them are databases and I could execute the queries fast others don't even have querying capabilities.

In order for a feature like this to be performant I would have to opt for a minimal set of operations that could be supported by each and every backend
