### ISSUE TITLE
Not caching on emulator or device

### ISSUE THREAD

**Issue by jeremiahlukus** [ivoleitao/stash#4]
**Describe the bug**
I am setting a cache policy of 1 day, I'd expect the cache.get method would return a value after navigating to a new screen. 

**To Reproduce**

```
  _getAudioFiles() async {
    final path = Directory.systemTemp.path;
    final cache = newHiveCache(path, maxEntries: 100, expiryPolicy: const CreatedExpiryPolicy(Duration(days: 1)));
    final value = await cache.get('audioFiles');
    if (value != null) {
      print("using cache");
      setState(() {
        _audioFiles = value;
      });
    } else {
      print("In else");
      var audioFiles = await MyApi().getAudioFiles();
      await cache.put('audioFiles', audioFiles);
      List<dynamic> value = await cache.get('audioFiles');
     print(value);  // its being printed
      setState(() {
        _audioFiles = value;
      });
    }
  }
  ```
  
  `value` is always return null therefore is always goes to my else statement. 
  
  
**Version**
 dart --version
Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "macos_x64"

**Additional context**
I am using this with stash_hive, another odd thing is i have to include stash in my pubspec to use `CreatedExpiryPolicy`.

**Comment by ivoleitao** [comment]
Hi!

I believe I know what's happening. If you do not provide a name for the cache I generate a UUID for the name and since you are initialising it every-time (you should probably use a singleton for it) it will get a new cache name every time. To be honest even with a singleton you will have the same problem as in every startup you will get a different cache name.

I should probably make this clear in the documentation to be honest and I will do that (either that or making name mandatory because this could be deceiving)

**Comment by jeremiahlukus** [comment]
Awesome thanks for the response, that answers my question ill give that a go.
