### ISSUE TITLE
stash_isar: Analysis issue

### ISSUE THREAD

**Issue by tjarvstrand** [ivoleitao/stash#42]
**Describe the bug**
The stash_isar package has a reported analysis issue on pub.dev: ` ERROR: Evaluation of this constant expression throws an exception. `

https://pub.dev/packages/stash_isar/score

**Comment by ivoleitao** [comment]
Hi thanks for the report. I was already aware of this problem but I hadn't opened an issue yet. This is a problem in the isar code generation. This does not happen on the CI build because I have ignored the *.g files 

```
analyzer:
  exclude:
    - lib/**.g.dart
```

but for some reason pub.dev ignores it and this error is reported. I've opened an issue in isar repo to track this as I can only fix it if the generated code is either changed or somewhat explicitly excluded from analysis. Here's the issue for tracing: https://github.com/isar/isar/issues/1057

**Comment by ivoleitao** [comment]
Still waiting for an answer from isar maintainers

**Comment by ivoleitao** [comment]
Still waiting for a response on the opened bug

**Comment by tjarvstrand** [comment]
There is no analysis issue reported for the stash_isar package on pub.dev anymore though.

**Comment by ivoleitao** [comment]
Oh thanks, I need to check then wasn't aware of that

**Comment by ivoleitao** [comment]
The error is not displayed anymore, clossing issue
